INSERT INTO UTILISATEURS (ID, LOGIN, PASSWORD) VALUES (1001, 'fatee', 'f@te25');
INSERT INTO UTILISATEURS (ID, LOGIN, PASSWORD) VALUES (1002, 'eni', 'eni24');
INSERT INTO UTILISATEURS (ID, LOGIN, PASSWORD) VALUES (1003, 'neruda', 'cia1D');
INSERT INTO UTILISATEURS (ID, LOGIN, PASSWORD) VALUES (1004, 'sam', 'chrIs9');
INSERT INTO UTILISATEURS (ID, LOGIN, PASSWORD) VALUES (1005, 'icy', '14Lam');